version: '3.0'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    volumes:
      - dbdata:/var/opt/mssql
  
  mongodb:
    image: mongo
  
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'

  redis:
    image: redis

  internal-gateway:
    image: 'microservice-demo/internal-gateway:${TAG:-latest}'
    build:
      context: ../../
      dockerfile: samples/MicroserviceDemo/gateways/InternalGateway.Host/Dockerfile
    depends_on:
      - redis
      - sqlserver
      - identity-service
      - product-service
      - blogging-service
  
  backend-admin-app-gateway:
    image: 'microservice-demo/backend-admin-app-gateway:${TAG:-latest}'
    build:
      context: ../../
      dockerfile: samples/MicroserviceDemo/gateways/BackendAdminAppGateway.Host/Dockerfile
    depends_on:
      - redis
      - sqlserver
      - identity-service
      - product-service
  
  public-website-gateway:
    image: 'microservice-demo/public-website-gateway:${TAG:-latest}'
    build:
      context: ../../
      dockerfile: samples/MicroserviceDemo/gateways/PublicWebSiteGateway.Host/Dockerfile
    depends_on:
      - redis
      - blogging-service
      - product-service
  
  blogging-service:
    image: 'microservice-demo/blogging-service:${TAG:-latest}'
    build:
      context: ../../
      dockerfile: samples/MicroserviceDemo/microservices/BloggingService.Host/Dockerfile
    depends_on:
      - mongodb
      - redis
  
  identity-service:
    image: 'microservice-demo/identity-service:${TAG:-latest}'
    build:
      context: ../../
      dockerfile: samples/MicroserviceDemo/microservices/IdentityService.Host/Dockerfile
    depends_on:
      - rabbitmq
      - redis
      - sqlserver
  
  product-service:
    image: 'microservice-demo/product-service:${TAG:-latest}'
    build:
      context: ../../
      dockerfile: samples/MicroserviceDemo/microservices/ProductService.Host/Dockerfile
    depends_on:
      - sqlserver
      - redis
  
  auth-server:
    image: 'microservice-demo/auth-server:${TAG:-latest}'
    build:
      context: ../../
      dockerfile: samples/MicroserviceDemo/applications/AuthServer.Host/Dockerfile
    depends_on:
      - redis
      - rabbitmq
      - identity-service
  
  backend-admin-app:
    image: 'microservice-demo/backend-admin-app:${TAG:-latest}'
    build:
      context: ../../
      dockerfile: samples/MicroserviceDemo/applications/BackendAdminApp.Host/Dockerfile
    depends_on:
      - backend-admin-app-gateway
  
  console-client-demo:
    image: 'microservice-demo/console-client-demo:${TAG:-latest}'
    build:
      context: ../../
      dockerfile: samples/MicroserviceDemo/applications/ConsoleClientDemo/Dockerfile
    depends_on:
      - internal-gateway
  
  public-website:
    image: 'microservice-demo/public-website:${TAG:-latest}'
    build:
      context: ../../
      dockerfile: samples/MicroserviceDemo/applications/PublicWebSite.Host/Dockerfile
    depends_on:
      - public-website-gateway

volumes:
  dbdata: