apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: blogging-service
  name: blogging-service
spec:
  ports:
  - name: "62157"
    port: 62157
    targetPort: 80
  selector:
    io.kompose.service: blogging-service
status:
  loadBalancer: {}
