apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: console-client-demo
  name: console-client-demo
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 80
  selector:
    io.kompose.service: console-client-demo
status:
  loadBalancer: {}
