apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: identity-service
  name: identity-service
spec:
  ports:
  - name: "63568"
    port: 63568
    targetPort: 80
  selector:
    io.kompose.service: identity-service
status:
  loadBalancer: {}
