apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: product-service
  name: product-service
spec:
  ports:
  - name: "60244"
    port: 60244
    targetPort: 80
  selector:
    io.kompose.service: product-service
status:
  loadBalancer: {}
