apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: public-website-gateway
  name: public-website-gateway
spec:
  ports:
  - name: "64897"
    port: 64897
    targetPort: 80
  selector:
    io.kompose.service: public-website-gateway
status:
  loadBalancer: {}
